export const User = [
  {
    name: "Agustina Martin Santana",
    password: "AMSantana13",
    role: "Técnico",
    ext: 41913,
    email: "tmartin@grancanaria.com",
  },
  {
    name: "Benita Ruiz Hernandez",
    password: "BRHernandez17",
    role: "Técnico",
    ext: 41917,
    email: "bruiz@grancanaria.com",
  },
  {
    name: "Carmen del Pilar Suarez Godoy",
    password: "CPSGodoy73",
    role: "Subalterna/o",
    ext: 19473,
    email: "csuarezg@grancanaria.com",
  },
  {
    name: "Cristina Marrero Suarez",
    password: "CMSuarez33",
    role: "Administrativa/o",
    ext: 41933,
    email: "cmarreros@grancanaria.com",
  },
  {
    name: "Juan Jose Alonso Moreno",
    password: "JJAMoreno21",
    role: "Delineante",
    ext: 41921,
    email: "jjalonsom@grancanaria.com",
  },
  {
    name: "Manuel Julian Perez Lorenzo",
    password: "MJPLorenzo26",
    role: "Técnico",
    ext: 41926,
    email: "mjperezl@grancanaria.com",
  },
  {
    name: "Maria Elena Moreno Davila",
    password: "MEMDavila24",
    role: "Técnico",
    ext: 41924,
    email: "emorenod@grancanaria.com",
  },
  {
    name: "Maria Francisca Gonzalez Jepsen",
    password: "MFGJepsen12",
    role: "Jefatura Negocido Administrativa/o",
    ext: 41912,
    email: "jepsen@grancanaria.com",
  },
  {
    name: "Samuel Aza Rodriguez",
    password: "SARofriguez28",
    role: "Técnico",
    ext: 41928,
    email: "sazar@grancanaria.com",
  },
  {
    name: "Soraya Paloma Palomo Medina",
    password: "SPPMedina11",
    role: "Jurídica/o",
    ext: 41911,
    email: "@grancanaria.com",
  },
  {
    name: "Teresa Pilar Rivero Ramos",
    password: "TPRRamos",
    role: "Jefatura de Servicio",
    ext: 19217,
    email: "privero@grancanaria.com",
  },
  {
    name: "Toñi Alvarez Martel",
    password: "TAMartel14",
    role: "Técnico",
    ext: 41914,
    email: "aalvarezm@grancanaria.com",
  },
  {
    name: "Alejandro Jose Cruz Santiago",
    password: "AJCSantiago0",
    role: "Informatica/o Practicas",
    ext: 0,
    email: "noe-ajcruzs@grancanaria.com",
  },
  {
    name: "Elena Medero Suarez",
    password: "EMRamos0",
    role: "Juridica/o Practicas",
    ext: 0,
    email: "noe-emederosr@grancanaria.com",
  },
  {
    name: "Selenia Cristina Vera Rodriguez",
    password: "SCVRodriguez0",
    role: "Ambientologa/o Practicas",
    ext: 0,
    email: "noe-scverar@grancanaria.com",
  },
  {
    name: "Victor Eduardo Castellano Araujo",
    password: "VECAraujo0",
    role: "Arquitecta/o Practicas",
    ext: 0,
    email: "noe-vecastellanoa@grancanaria.com",
  },
];